\documentclass{article}
\usepackage{graphicx}
\usepackage[left=1.00in, right=1.00in, top=1.00in, bottom=1.00in]{geometry}

\DeclareGraphicsExtensions{.png,.jpg}

\title{Appendix}
\author{Daniel Chen \\ CUMC}
\date{}

<<set-options, include=FALSE>>=
opts_chunk$set(cashe=TRUE, dev='png', dpi=300, tidy=TRUE)
@

\begin{document}
\maketitle
\tableofcontents

\section{Plotting Function}
\label{sec:plot-function}
For the plots, x-axis is time, y-axis is processing unit activation value

<<plotting function>>=
plot.thesis.data <- function(data, numAgents, numTimeTicks, subx = 0, xmin = 0, xmax = 10)
  {
  x <- read.csv(data, header=FALSE, stringsAsFactors=FALSE)

  names(x) <- c("time", "agent",
                       "p1", "p2", "p3", "p4", "p5",
                       "n1", "n2", "n3", "n4", "n5")



  for (i in 3:12) {
    x[ ,i] <- as.numeric(x[ ,i])
  }

  x.1 <- x[seq(1, numTimeTicks * numAgents ,numAgents),]
  x.2 <- x[seq(2, numTimeTicks * numAgents ,numAgents),]
  x.3 <- x[seq(3, numTimeTicks * numAgents ,numAgents),]
  x.4 <- x[seq(4, numTimeTicks * numAgents ,numAgents),]
  x.5 <- x[seq(5, numTimeTicks * numAgents ,numAgents),]

  x.1.ave.pos <- apply(x.1[,c(3,4,5,6,7)],1, mean)
  x.1.ave.neg <- apply(x.1[,c(8,9,10,11,12)],1,mean)

  x.2.ave.pos <- apply(x.2[,c(3,4,5,6,7)],1,mean)
  x.2.ave.neg <- apply(x.2[,c(8,9,10,11,12)],1,mean)

  x.3.ave.pos <- apply(x.3[,c(3,4,5,6,7)],1,mean)
  x.3.ave.neg <- apply(x.3[,c(8,9,10,11,12)],1,mean)

  x.4.ave.pos <- apply(x.4[,c(3,4,5,6,7)],1,mean)
  x.4.ave.neg <- apply(x.4[,c(8,9,10,11,12)],1,mean)

  x.5.ave.pos <- apply(x.5[,c(3,4,5,6,7)],1,mean)
  x.5.ave.neg <- apply(x.5[,c(8,9,10,11,12)],1,mean)

  if (subx == 0)
  {
    print(head(x, numAgents))
    print(tail(x, numAgents))

    plot(x.1.ave.pos,lty=1,col=1,type="b",ylim=c(0,1))
    lines(x.1.ave.neg, lty=2, col=1, type="b", lwd=3)

    lines(x.2.ave.neg,ylim=c(0,1),lty=1,col=2,type="b")
    lines(x.2.ave.neg,lty=2,col=2,type="b", lwd=3)

    lines(x.3.ave.neg,lty=1,col=3,type="b")
    lines(x.3.ave.neg,lty=2,col=3,type="b", lwd=3)

    lines(x.4.ave.neg,lty=1,col=4,type="b")
    lines(x.4.ave.neg,lty=2,col=4,type="b", lwd=3)

    lines(x.5.ave.neg,lty=1,col=5,type="b")
    lines(x.5.ave.neg,lty=2,col=5,type="b", lwd=3)
  }

  if (subx == 1)
    {
      print(head(x[xmax,], numAgents))
      print(tail(x[xmax,], numAgents))

      plot(x.1.ave.pos, lty = 1, col = 1, type = "b", ylim = c(0, 1), xlim = c(xmin, xmax))
      lines(x.1.ave.neg, lty=2, col=1, type="b", lwd=3)

      lines(x.2.ave.neg,ylim=c(0,1),lty=1,col=2,type="b")
      lines(x.2.ave.neg,lty=2,col=2,type="b", lwd=3)

      lines(x.3.ave.neg,lty=1,col=3,type="b")
      lines(x.3.ave.neg,lty=2,col=3,type="b", lwd=3)

      lines(x.4.ave.neg,lty=1,col=4,type="b")
      lines(x.4.ave.neg,lty=2,col=4,type="b", lwd=3)

      lines(x.5.ave.neg,lty=1,col=5,type="b")
      lines(x.5.ave.neg,lty=2,col=5,type="b", lwd=3)
    }
  }
@

\newpage

\section{Sanity Checks}
\label{sec:sanity-checks}

\subsection{Sanity Check 1}
\label{sec:sanity1}
Sanity Case:
\begin{itemize}
  \item Agents Activated: Agent 1 ont
  \item Valence Bank: positive only
  \begin{itemize}
      \item Valence bank activation: 1's
  \end{itemize}
  \item Valence bank Weights: random
  \begin{itemize}
      \item opposite 0
      \item corresponding 0
      \item carry over = 0.2
      \item bias = 0
      \item decay = -0.5
  \end{itemize}
  \item Network: circle
\end{itemize}

<<plot-sanity-1, fig.cap="Sanity Checking 1", fig.show='asis'>>=
plot.thesis.data("/home/dchen/git/repast-neural-network-agent-based-model/R/data/agent1pos1.csv", 10, 10)
@

in scetion \ref{sec:sanity-checks}, there was all the plots

in scetion \ref{sec:sanity1}, there was a plot

\newpage
\subsection{Sanity Check 2}
\label{sec:sanity2}
Sanity Case:
\begin{itemize}
  \item Agents Activated: Agent 1 ont
  \item Valence Bank: positive only
  \begin{itemize}
      \item Valence bank activation: \textbf{random}
  \end{itemize}
  \item Valence bank Weights: random
  \begin{itemize}
      \item opposite 0
      \item corresponding 0
      \item carry over = 0.2
      \item bias = 0
      \item decay = -0.5
  \end{itemize}
  \item Network: circle
\end{itemize}

<<plot-sanity-2, fig.cap="Sanity Checking 2", fig.show='asis'>>=
plot.thesis.data("/home/dchen/git/repast-neural-network-agent-based-model/R/data/agent1posrandom.csv", 10, 10)
@

\newpage
\subsection{Sanity Check 3}
\label{sec:sanity3}
Sanity Case:
\begin{itemize}
  \item Agents Activated: Agent 1 ont
  \item Valence Bank: \textbf{both}
  \begin{itemize}
      \item Valence bank activation: random
  \end{itemize}
  \item Valence bank Weights: random
  \begin{itemize}
      \item opposite 0
      \item corresponding 0
      \item carry over = 0.2
      \item bias = 0
      \item decay = -0.5
  \end{itemize}
  \item Network: circle
\end{itemize}

<<plot-sanity-3, fig.cap="Sanity Checking 3", fig.show='asis'>>=
plot.thesis.data("/home/dchen/git/repast-neural-network-agent-based-model/R/data/agent1bothrandom.csv", 10, 10)
@

\newpage
\subsection{Sanity Check 4}
\label{sec:sanity4}
Sanity Case:
\begin{itemize}
  \item Agents Activated: Agent 1 ont
  \item Valence Bank: both
  \begin{itemize}
      \item Valence bank activation: random
  \end{itemize}
  \item Valence bank Weights: random
  \begin{itemize}
      \item opposite \textbf{-0.2}
      \item corresponding \textbf{0.5}
      \item carry over = 0.2
      \item bias = 0
      \item decay = -0.5
  \end{itemize}
  \item Network: circle
\end{itemize}

<<plot-sanity-4, fig.cap="Sanity Checking 4", fig.show='asis'>>=
plot.thesis.data("/home/dchen/git/repast-neural-network-agent-based-model/R/data/agent1bothrandom-weights.csv", 10, 10)
@

\newpage
\subsection{Sanity Check 5}
\label{sec:sanity5}
Sanity Case:
\begin{itemize}
  \item Agents Activated: \textbf{All}
  \item Valence Bank: both
  \begin{itemize}
      \item Valence bank activation: random
  \end{itemize}
  \item Valence bank Weights: random
  \begin{itemize}
      \item opposite -0.2
      \item corresponding 0.5
      \item carry over = 0.2
      \item bias = 0
      \item decay = -0.5
  \end{itemize}
  \item Network: circle
\end{itemize}

<<plot-sanity-5, fig.cap="Sanity Checking 5", fig.show='asis'>>=
plot.thesis.data("/home/dchen/git/repast-neural-network-agent-based-model/R/data/randomvaluesetweight.csv", 10, 10)
@

\newpage
\section{Output}
\subsection{Output 1}
\label{sec:output1}
Output Data
\begin{itemize}
  \item Agents Activated: 1
  \item Valence Bank: both
  \begin{itemize}
      \item Valence bank activation: random
  \end{itemize}
  \item Valence bank Weights: random
  \begin{itemize}
      \item opposite -0.2
      \item corresponding 0.5
      \item carry over = 0.2
      \item bias = 0
      \item decay = -0.5
  \end{itemize}
  \item Network: circle
  \item Random number: read in from file
  \item Processing units per valence bank: 5
  \item number of agents: 10
  \item number of time ticks: 10,000
\end{itemize}

\subsubsection{First 100 time ticks}
<<plot-output-1, fig.cap="Output 1, first 100 time ticks", fig.show='asis', cache=TRUE>>=
plot.thesis.data("/home/dchen/git/repast-neural-network-agent-based-model/R/data/agent1-both-random-weights-10k.csv", 10, 10000, 1, 0, 100)
@

\newpage
\subsubsection{All time ticks}
<<plot-output-1a, fig.cap="Output 1, all time ticks", fig.show='asis', cache=TRUE>>=
plot.thesis.data("/home/dchen/git/repast-neural-network-agent-based-model/R/data/agent1-both-random-weights-10k.csv", 10, 10000)
@

\end{document}
